http {
    include /etc/nginx/snippets/ruconet-http.conf;

    map $http_x_forwarded_proto $forwarded_https {
        https   on;
        default "";
    }

    # Roundcube
    server {
        listen mail.ruconet.internal:443 ssl;

        include /etc/nginx/snippets/ruconet.conf;
        include /etc/nginx/snippets/ruconet-gateway.conf;

        root  /var/www/roundcube/public_html;
        index index.php;

        client_max_body_size 50m;

        location ~ ^/(config|temp|logs|vendor|bin|SQL)/ {
            return 404;
        }

        location ~ /\. {
            return 404;
        }

        location = /favicon.ico {
            rewrite ^ /static.php/skins/elastic/images/favicon.ico last;
        }

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ ^.+\.php(/.*)?$ {
            fastcgi_split_path_info ^(.+\.php)(/.*)$;

            try_files $fastcgi_script_name =404;

            include /etc/nginx.d/snippets/fastcgi.conf;
            fastcgi_pass 127.0.0.1:9000;
        }
    }

    # Rspamd
    server {
        listen mail.ruconet.internal:11334 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        location / {
            proxy_pass http://127.0.0.1:11334;

            proxy_http_version 1.1;

            proxy_set_header Host              $host;
            proxy_set_header Connection        "";
            proxy_set_header X-Real-IP         "";
            proxy_set_header X-Forwarded-For   "";
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

            proxy_buffer_size        64k;
            proxy_buffers            8 128k;
            proxy_busy_buffers_size  256k;

            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
        }
    }

    # Mail Auth
    server {
        listen mail.ruconet.internal:10080 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        location / {
            proxy_pass http://127.0.0.1:10080;

            proxy_http_version 1.0;
        }
    }
}
