stream {
    include /etc/nginx/snippets/ruconet-stream.conf;

    # SMTP
    server {
        listen mail.ruconet.internal:25 ssl proxy_protocol;

        include /etc/nginx/snippets/ruconet.conf;

        set_real_ip_from gateway.ruconet.internal;

        proxy_pass 127.0.0.1:25;
        proxy_protocol on;
        proxy_timeout 30m;
    }

    # IMAP
    server {
        listen mail.ruconet.internal:143 ssl proxy_protocol;

        include /etc/nginx/snippets/ruconet.conf;

        set_real_ip_from gateway.ruconet.internal;

        proxy_pass 127.0.0.1:143;
        proxy_protocol on;
        proxy_timeout 30m;
    }

    # Submission (Mail Proxy)
    server {
        listen mail.ruconet.internal:10025 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        proxy_pass 127.0.0.1:10025;
        proxy_timeout 30m;
    }

    # Submission
    server {
        listen mail.ruconet.internal:587 ssl;

        include /etc/nginx/snippets/ruconet.conf;

        proxy_pass 127.0.0.1:587;
        proxy_timeout 30m;
    }

    # PostgreSQL (Client)
    server {
        listen 127.0.0.1:5432;

        proxy_pass db.ruconet.internal:5432;
        proxy_timeout 12h;

        proxy_ssl on;
        include /etc/nginx/snippets/ruconet-proxy.conf;
    }

    # Mail Relay (Client)
    server {
        listen 127.0.0.1:10587;

        proxy_pass mail-relay.ruconet.internal:587;
        proxy_timeout 30m;

        proxy_ssl on;
        include /etc/nginx/snippets/ruconet-proxy.conf;
    }
}
