dovecot_config_version  = 2.4.1
dovecot_storage_version = 2.4.0

base_dir = /run/dovecot

log_path      = /dev/stderr
info_log_path = /dev/stderr

protocols = imap lmtp sieve

listen = 127.0.0.1

ssl = no

auth_allow_cleartext = yes

auth_mechanisms = plain login

mail_driver = maildir
mail_path   = ~/Maildir
mail_home   = /srv/vmail/%{user | domain}/%{user | username}
mail_uid    = vmail
mail_gid    = vmail

mailbox_list_layout = maildir++

haproxy_trusted_networks = 127.0.0.1/32
login_trusted_networks   = 127.0.0.1/32

sql_driver = pgsql

pgsql 127.0.0.1 {
  parameters {
    dbname   = mail
    user     = mail
    password = ${MAIL_DB_PASSWORD}
    sslmode  = disable
  }
}

passdb_default_password_scheme = ARGON2ID

passdb sql {
  query = SELECT username || '@' || domain AS "user", password FROM accounts WHERE username = '%{user | username | lower}' AND domain = '%{user | domain | lower}' AND active
}

userdb sql {
  query = SELECT username || '@' || domain AS "user" FROM accounts WHERE username = '%{user | username | lower}' AND domain = '%{user | domain | lower}' AND active
  iterate_query = SELECT username || '@' || domain AS "user" FROM accounts WHERE active
}

service imap-login {
  inet_listener imap {
    port    = 143
    haproxy = yes
  }
  inet_listener imap-internal {
    port = 1143
  }
  inet_listener imaps {
    port = 0
  }
}

service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}

service lmtp {
  inet_listener lmtp {
    port = 24
  }
}

service auth {
  inet_listener auth {
    port = 12345
  }
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

protocol imap {
  mail_plugins {
    imap_sieve = yes
  }
}

sieve_script personal {
  type        = personal
  driver      = file
  path        = ~/sieve
  active_path = ~/.dovecot.sieve
}

sieve_script default {
  type   = default
  name   = roundcube
  driver = file
  path   = /etc/dovecot/sieve/default.sieve
}

sieve_plugins {
  sieve_imapsieve   = yes
  sieve_extprograms = yes
}

sieve_global_extensions = imapsieve vnd.dovecot.pipe

sieve_pipe_bin_dir = /etc/dovecot/sieve

mailbox Junk {
  special_use = \Junk
  auto        = subscribe

  sieve_script learn-spam {
    type  = before
    cause = copy
    path  = /etc/dovecot/sieve/learn-spam.sieve
  }
}

imapsieve_from Junk {
  sieve_script learn-ham {
    type  = before
    cause = copy
    path  = /etc/dovecot/sieve/learn-ham.sieve
  }
}

mailbox Drafts {
  special_use = \Drafts
  auto        = subscribe
}

mailbox Sent {
  special_use = \Sent
  auto        = subscribe
}

mailbox Trash {
  special_use = \Trash
  auto        = subscribe
}

mailbox Archive {
  special_use = \Archive
  auto        = subscribe
}
