ServerRoot /etc/apache2
ServerName localhost

Listen 127.0.0.1:8080

PidFile /run/apache2/apache2.pid
User    www-data
Group   www-data

LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so
LoadModule authz_core_module  /usr/lib/apache2/modules/mod_authz_core.so
LoadModule dir_module         /usr/lib/apache2/modules/mod_dir.so
LoadModule env_module         /usr/lib/apache2/modules/mod_env.so
LoadModule mime_module        /usr/lib/apache2/modules/mod_mime.so
LoadModule rewrite_module     /usr/lib/apache2/modules/mod_rewrite.so
LoadModule php_module         /usr/lib/apache2/modules/libphp8.4.so

StartServers           3
MinSpareServers        2
MaxSpareServers        6
MaxRequestWorkers      16
MaxConnectionsPerChild 500

ErrorLog  /dev/stderr
LogLevel  warn

ServerTokens    Prod
ServerSignature Off
TraceEnable     Off

TypesConfig     /etc/mime.types
LimitRequestBody 54525952

PassEnv ROUNDCUBE_DB_PASSWORD ROUNDCUBE_DES_KEY MAIL_DB_PASSWORD

php_admin_value upload_max_filesize 50M
php_admin_value post_max_size       52M
php_admin_value memory_limit        256M
php_admin_value date.timezone       Asia/Tokyo
php_admin_value error_log           /dev/stderr
php_admin_flag  log_errors          on
php_admin_flag  display_errors      off

DocumentRoot /opt/roundcube/public_html

<Directory />
    AllowOverride None
    Require all denied
</Directory>

<Directory /opt/roundcube/public_html>
    Require all granted

    DirectoryIndex index.php
    AcceptPathInfo On

    RewriteEngine On
    RewriteRule ^favicon\.ico$ static.php/skins/elastic/images/favicon.ico [L]
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>

<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
