[roundcube]
user  = www-data
group = www-data

listen = 127.0.0.1:9000

listen.allowed_clients = 127.0.0.1

env[ROUNDCUBE_DB_PASSWORD] = $ROUNDCUBE_DB_PASSWORD
env[ROUNDCUBE_DES_KEY]     = $ROUNDCUBE_DES_KEY
env[MAIL_DB_PASSWORD]      = $MAIL_DB_PASSWORD

pm                   = dynamic
pm.max_children      = 16
pm.start_servers     = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests      = 500

catch_workers_output = yes
decorate_workers_output = no

php_admin_value[upload_max_filesize] = 50M
php_admin_value[post_max_size]       = 52M
php_admin_value[memory_limit]        = 256M
php_admin_value[date.timezone]       = Asia/Tokyo
php_admin_value[error_log]           = /dev/stderr
php_admin_flag[log_errors]           = on
php_admin_flag[display_errors]       = off
